FROM webhippie/alpine:latest-amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Shellcheck" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/shellcheck"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

RUN wget -q -O /usr/bin/shellcheck https://storage.googleapis.com/shellcheck/shellcheck-v0.7.0.linux-x86_64 && \
  chmod +x /usr/bin/shellcheck
